const data = [
    {nazevSuroviny:"česnek"},
    {nazevSuroviny:"cibule"},
    {nazevSuroviny:"vejce"},
    {nazevSuroviny:"olivový olej"},
    {nazevSuroviny:"ghee"},
    {nazevSuroviny:"sádlo"},
    {nazevSuroviny:"erythritol"},
    {nazevSuroviny:"čerstvá paprika"},
    {nazevSuroviny:"smetana na šlehání 31%"},
    {nazevSuroviny:"mrkev"},
    {nazevSuroviny:"rajčatový protlak"},
    {nazevSuroviny:"mletý římský kmín"},
    {nazevSuroviny:"majonéza"},
    {nazevSuroviny:"kokosové mléko"},
    {nazevSuroviny:"balzamikový ocet"},
    {nazevSuroviny:"stroužek česneku"},
    {nazevSuroviny:"kešu"},
    {nazevSuroviny:"čerstvé žampióny"},
    {nazevSuroviny:"uzená paprika"},
    {nazevSuroviny:"vývar"},
    {nazevSuroviny:"čerstvá petrželka"},
    {nazevSuroviny:"sladká paprika"},
    {nazevSuroviny:"chilli paprička"},
    {nazevSuroviny:"čerstvý koriandr"},
    {nazevSuroviny:"mandlová mouka"},
    {nazevSuroviny:"šalotka"},
    {nazevSuroviny:"máslová dýně"},
    {nazevSuroviny:"cuketa"},
    {nazevSuroviny:"máslo"},
    {nazevSuroviny:"slanina"},
    {nazevSuroviny:"pekany"},
    {nazevSuroviny:"čerstvý zázvor"},
    {nazevSuroviny:"květák"},
    {nazevSuroviny:"dýně hokkaido"},
    {nazevSuroviny:"jablečný ocet"},
    {nazevSuroviny:"chilli koření"},
    {nazevSuroviny:"bobkový list"},
    {nazevSuroviny:"mletá skořice"},
    {nazevSuroviny:"rajčata"},
    {nazevSuroviny:"limetka"},
    {nazevSuroviny:"sezamová semínka"},
    {nazevSuroviny:"batáty"},
    {nazevSuroviny:"hořčice"},
    {nazevSuroviny:"celer"},
    {nazevSuroviny:"smetanový krémový sýr"},
    {nazevSuroviny:"konzervovaná loupaná rajčata"},
    {nazevSuroviny:"avokádo"},
    {nazevSuroviny:"kokosový olej"},
    {nazevSuroviny:"datle"},
    {nazevSuroviny:"hořké kakao"},
    {nazevSuroviny:"citrónová šťáva"},
    {nazevSuroviny:"lahůdková cibulka"},
    {nazevSuroviny:"hořká vysokoprocentní čokoláda"},
    {nazevSuroviny:"jablka"},
    {nazevSuroviny:"cherry rajčata"},
    {nazevSuroviny:"psyllium"},
    {nazevSuroviny:"prášek do pečiva (s vinným kamenem)"},
    {nazevSuroviny:"kokosová mouka"},
    {nazevSuroviny:"čerstvá bazalka"},
    {nazevSuroviny:"parmazán"},
    {nazevSuroviny:"mletý kmín"},
    {nazevSuroviny:"mletý koriandr"},
    {nazevSuroviny:"vanilkový lusk"},
    {nazevSuroviny:"salátová okurka"},
    {nazevSuroviny:"nové koření"},
    {nazevSuroviny:"bílek"},
    {nazevSuroviny:"kvalitní sójová omáčka"},
    {nazevSuroviny:"citrón"},
    {nazevSuroviny:"žloutek"},
    {nazevSuroviny:"chilli vločky"},
    {nazevSuroviny:"pórek"},
    {nazevSuroviny:"mleté maso (mix vepřové a hovězí)"},
    {nazevSuroviny:"slunečnicová semínka"},
    {nazevSuroviny:"smetana kysaná 15%"},
    {nazevSuroviny:"strouhaný kokos"},
    {nazevSuroviny:"losos"},
    {nazevSuroviny:"lněná semínka"},
    {nazevSuroviny:"vepřový bůček (bez kůže a kosti)"},
    {nazevSuroviny:"kedlubna"},
    {nazevSuroviny:"mleté hovězí maso"},
    {nazevSuroviny:"mletá kurkuma"},
    {nazevSuroviny:"petržel"},
    {nazevSuroviny:"kuřecí prsní řízky"},
    {nazevSuroviny:"želatina bez příchuti"},
    {nazevSuroviny:"bílý tučný 10% jogurt"},
    {nazevSuroviny:"ředkev"},
    {nazevSuroviny:"čerstvý špenát"},
    {nazevSuroviny:"sušený tymián"},
    {nazevSuroviny:"sušená majoránka"},
    {nazevSuroviny:"sýr Čedar"},
    {nazevSuroviny:"nakládané kapary"},
    {nazevSuroviny:"vepřová krkovice (bez kosti)"},
    {nazevSuroviny:"kysané zelí"},
    {nazevSuroviny:"kmín"},
    {nazevSuroviny:"med"},
    {nazevSuroviny:"sušená rajčata (v olivovém oleji)"},
    {nazevSuroviny:"čerstvý rozmarýn"},
    {nazevSuroviny:"svitek skořice"},
    {nazevSuroviny:"strouhaný tvrdý sýr"},
    {nazevSuroviny:"kuřecí stehenní řízky"},
    {nazevSuroviny:"tapioková mouka"},
    {nazevSuroviny:"hvězdička badyánu"},
    {nazevSuroviny:"coconut aminos"},
    {nazevSuroviny:"řapíkatý celer"},
    {nazevSuroviny:"lilek"},
    {nazevSuroviny:"bílé hlávkové zelí"},
    {nazevSuroviny:"sušená šunka"},
    {nazevSuroviny:"ocet"},
    {nazevSuroviny:"červená řepa"},
    {nazevSuroviny:"hlávková kapusta"},
    {nazevSuroviny:"mleté vepřové maso"},
    {nazevSuroviny:"sušený rozmarýn"},
    {nazevSuroviny:"kuřecí stehna (včetně kostí a kůže)"},
    {nazevSuroviny:"kopr"},
    {nazevSuroviny:"rybí omáčka"},
    {nazevSuroviny:"sušené oregáno"},
    {nazevSuroviny:"káva (zrnková či mletá)"},
    {nazevSuroviny:"černé olivy bez pecky"},
    {nazevSuroviny:"růžičková kapusta"},
    {nazevSuroviny:"vlašské ořechy"},
    {nazevSuroviny:"polníček"},
    {nazevSuroviny:"červená curry pasta"},
    {nazevSuroviny:"sušený zázvor"},
    {nazevSuroviny:"vinný ocet"},
    {nazevSuroviny:"dýňová semínka"},
    {nazevSuroviny:"vepřová panenka"},
    {nazevSuroviny:"čerstvý kozí sýr"},
    {nazevSuroviny:"hovězí kližka"},
    {nazevSuroviny:"sušené houby"},
    {nazevSuroviny:"čerstvý křen"},
    {nazevSuroviny:"creme fraiche (30% zakysaná smetana)"},
    {nazevSuroviny:"banán"},
    {nazevSuroviny:"hlíva ústřičná"},
    {nazevSuroviny:"mozzarela"},
    {nazevSuroviny:"mandle"},
    {nazevSuroviny:"hřebíček"},
    {nazevSuroviny:"brokolice"},
    {nazevSuroviny:"zelené fazolky"},
    {nazevSuroviny:"sušené brusinky"},
    {nazevSuroviny:"kvalitní klobása"},
    {nazevSuroviny:"krevety (syrové, oloupané)"},
    {nazevSuroviny:"ledový salát"},
    {nazevSuroviny:"směs listových salátů"},
    {nazevSuroviny:"obrané maso z uvařených vepřových žebírek"},
    {nazevSuroviny:"měkký tučný tvaroh"},
    {nazevSuroviny:"vařená červená řepa"},
    {nazevSuroviny:"rum"},
    {nazevSuroviny:"čerstvá máta"},
    {nazevSuroviny:"hořčičná semínka"},
    {nazevSuroviny:"sušený česnek"},
    {nazevSuroviny:"niva"},
    {nazevSuroviny:"bok choy (pak choi)"},
    {nazevSuroviny:"sezamový olej"},
    {nazevSuroviny:"kakaové máslo"},
    {nazevSuroviny:"sýr Halloumi"},
    {nazevSuroviny:"olomoucké tvarůžky"},
    {nazevSuroviny:"upečené kachní maso"},
    {nazevSuroviny:"čerstvý tymián"},
    {nazevSuroviny:"grilovací koření"},
    {nazevSuroviny:"maliny"},
    {nazevSuroviny:"ředkvičky"},
    {nazevSuroviny:"červené hlávkové zelí"},
    {nazevSuroviny:"muškátový květ"},
    {nazevSuroviny:"chia semínka"},
    {nazevSuroviny:"baby špenát"},
    {nazevSuroviny:"vepřový bůček (s kůží, bez kosti)"},
    {nazevSuroviny:"hrušky"},
    {nazevSuroviny:"vepřová plec"},
    {nazevSuroviny:"kuřecí křídla (včetně špiček)"},
    {nazevSuroviny:"sušené švestky"},
    {nazevSuroviny:"kadeřávek"},
    {nazevSuroviny:"uzený losos"},
    {nazevSuroviny:"rukola"},
    {nazevSuroviny:"vepřová žebra"},
    {nazevSuroviny:"sýr Gouda"},
    {nazevSuroviny:"garam masala"},
    {nazevSuroviny:"šťáva z limetky"},
    {nazevSuroviny:"mletý mák"},
    {nazevSuroviny:"mascarpone"},
    {nazevSuroviny:"kokosové máslo"},
    {nazevSuroviny:"listový salát"},
    {nazevSuroviny:"medvědí česnek"},
    {nazevSuroviny:"stvol citrónové trávy"},
    {nazevSuroviny:"fenykl"},
    {nazevSuroviny:"perníkové koření"},
    {nazevSuroviny:"tuřín"},
    {nazevSuroviny:"vepřové koleno (s kostí a kůží)"},
    {nazevSuroviny:"vařené hovězí maso"},
    {nazevSuroviny:"muškátový oříšek"},
    {nazevSuroviny:"krůtí maso"},
    {nazevSuroviny:"filety z tresky"},
    {nazevSuroviny:"tuňák ve vlastní šťávě"},
    {nazevSuroviny:"sýr cottage"},
    {nazevSuroviny:"kari koření"},
    {nazevSuroviny:"pomeranč"},
    {nazevSuroviny:"krůtí prsa"},
    {nazevSuroviny:"špek"},
    {nazevSuroviny:"zelený chřest"},
    {nazevSuroviny:"sýr Feta"},
    {nazevSuroviny:"jalapeňo paprička"},
    {nazevSuroviny:"rýžový ocet"},
    {nazevSuroviny:"piniové oříšky"},
    {nazevSuroviny:"nakládané feferonky (ve slano-kyselém nálevu)"},
    {nazevSuroviny:"tuňák ve vlastní šťávě zbavený nálevu"},
    {nazevSuroviny:"plnotučné mléko"},
    {nazevSuroviny:"cayenský pepř"},
    {nazevSuroviny:"suché bílé víno"},
    {nazevSuroviny:"směs semínek a ořechů"},
    {nazevSuroviny:"jehněčí mleté maso"},
    {nazevSuroviny:"vepřová játra"},
    {nazevSuroviny:"domácí perníkové koření"},
    {nazevSuroviny:"palice česneku"},
    {nazevSuroviny:"limetový list (kaffir)"},
    {nazevSuroviny:"hovězí svíčková"},
    {nazevSuroviny:"kachna (vcelku, bez drobů)"},
    {nazevSuroviny:"rajčatová passata"},
    {nazevSuroviny:"kosti na vývar"},
    {nazevSuroviny:"hovězí zadní"},
    {nazevSuroviny:"nízký roštěnec"},
    {nazevSuroviny:"kuřecí paličky (spodní stehna)"},
    {nazevSuroviny:"směs ořechů"},
    {nazevSuroviny:"čerstvé jahody"},
    {nazevSuroviny:"tvrdá mozzarella"},
    {nazevSuroviny:"sýr Brie"},
    {nazevSuroviny:"odřezky z kuřete"},
    {nazevSuroviny:"slunečnicové máslo"},
    {nazevSuroviny:"ricotta"},
    {nazevSuroviny:"lískové ořechy"},
    {nazevSuroviny:"polotvrdý kozí sýr"},
    {nazevSuroviny:"vepřové sádlo na škvaření"},
    {nazevSuroviny:"kvalitní špekáčky"},
    {nazevSuroviny:"patizon"},
    {nazevSuroviny:"tvrdý sýr"},
    {nazevSuroviny:"černý kořen"},
    {nazevSuroviny:"sušená vanilka"},
    {nazevSuroviny:"jedlé kaštany"},
    {nazevSuroviny:"práškový pektin"},
    {nazevSuroviny:"krůtí stehno (včetně kostí a kůže)"},
    {nazevSuroviny:"mletý fenykl"},
    {nazevSuroviny:"cornichons"},
    {nazevSuroviny:"Lučina"},
    {nazevSuroviny:"králičí stehna (včetně kostí)"},
    {nazevSuroviny:"sušená citrónová kůra"},
    {nazevSuroviny:"koření pěti vůní"},
    {nazevSuroviny:"kachní stehna"},
    {nazevSuroviny:"hovězí přední s kostí"},
    {nazevSuroviny:"hovězí líčka"},
    {nazevSuroviny:"jalovec"},
    {nazevSuroviny:"švestky"},
    {nazevSuroviny:"borůvky"},
    {nazevSuroviny:"kakaová hmota"},
    {nazevSuroviny:"mango"},
    {nazevSuroviny:"kokosové lupínky"},
    {nazevSuroviny:"flank steak"},
    {nazevSuroviny:"čerstvá šalvěj"},
    {nazevSuroviny:"uvařené či upečené krůtí maso"},
    {nazevSuroviny:"řasa nori (plátek)"},
    {nazevSuroviny:"tamarind"},
    {nazevSuroviny:"ovčí sýr typu feta"},
    {nazevSuroviny:"tahini"},
    {nazevSuroviny:"červené víno"},
    {nazevSuroviny:"kuřecí játra"},
    {nazevSuroviny:"sterilované feferonky"},
    {nazevSuroviny:"hovězí oháňka"},
    {nazevSuroviny:"výhonky z řepy"},
    {nazevSuroviny:"hermelín"},
    {nazevSuroviny:"grana padano"},
    {nazevSuroviny:"mandlové máslo"},
    {nazevSuroviny:"žlutá curry pasta"},
    {nazevSuroviny:"mangold"},
    {nazevSuroviny:"škvarky"},
    {nazevSuroviny:"hovězí plec"},
    {nazevSuroviny:"pastinák"},
    {nazevSuroviny:"kachních prsa (s kůží)"},
    {nazevSuroviny:"loupané jedlé kaštany "},
    {nazevSuroviny:"kapr (včetně hlavy, kostí, kůže)"},
    {nazevSuroviny:"smažené vepřové kůže Chicharones"},
    {nazevSuroviny:"králičí játra"},
    {nazevSuroviny:"růžový pepř"},
    {nazevSuroviny:"mleté krůtí maso"},
    {nazevSuroviny:"brynza"},
    {nazevSuroviny:"vepřové nožičky"},
    {nazevSuroviny:"vepřový jazyk"},
    {nazevSuroviny:"vepřové srdce"},
    {nazevSuroviny:"kachní játra"},
    {nazevSuroviny:"kančí plec"},
    {nazevSuroviny:"sušené fíky"},
    {nazevSuroviny:"voda z mladého kokosu"},
    {nazevSuroviny:"třešně"},
    {nazevSuroviny:"klobása Chorizo"},
    {nazevSuroviny:"kokosový cukr"},
    {nazevSuroviny:"Jidášovo ucho (sušené)"},
    {nazevSuroviny:"čínské zelí"},
    {nazevSuroviny:"hovězí morkové kosti"},
    {nazevSuroviny:"datlové balzamiko"},
    {nazevSuroviny:"zelené plantainy"},
    {nazevSuroviny:"mleté telecí maso"},
    {nazevSuroviny:"vepřová pečeně"},
    {nazevSuroviny:"mleté řecké seno (pískavice)"},
    {nazevSuroviny:"pistáciové oříšky"},
    {nazevSuroviny:"konzervované sardinky v olivovém oleji"},
    {nazevSuroviny:"hovězí žebra"},
    {nazevSuroviny:"ostružiny"},
    {nazevSuroviny:"sterilované žampióny"},
    {nazevSuroviny:"jedlá soda"},
    {nazevSuroviny:"smetana na vaření 12 %"},
    {nazevSuroviny:"zelená curry pasta"},
    {nazevSuroviny:"kuřecí stehenní řízek (s kůží, bez kosti)"},
    {nazevSuroviny:"šafrán"},
    {nazevSuroviny:"krevety (syrové, neloupané)"},
    {nazevSuroviny:"čerstvé hřiby"},
    {nazevSuroviny:"camembert"},
    {nazevSuroviny:"mražený špenát"},
    {nazevSuroviny:"čerstvý estragon"},
    {nazevSuroviny:"křepelčí vejce"},
    {nazevSuroviny:"mungo klíčky"},
    {nazevSuroviny:"jelení maso (plec)"},
    {nazevSuroviny:"dušená vepřová šunka"},
    {nazevSuroviny:"houby enoki"},
    {nazevSuroviny:"pecorino"},
    {nazevSuroviny:"pancetta"}
]

module.exports = data;

